### ISSUE TITLE
What would an auto-release workflow look like?

### ISSUE THREAD

**Issue by epage** [sunng87/cargo-release#117]
Something I've been considering is the idea of auto-releasing after each PR but the question is "how?"
- Determine bump level
- Ensure we don't get into an infinite loop (a release causes a commit which causes a release)
- Any changelist management?

**Comment by epage** [comment]
One approach I just came across via [awesome-rust](https://github.com/rust-unofficial/awesome-rust#development-tools) is [semantic](https://github.com/semantic-rs/semantic-rs/blob/master/src/main.rs) which uses clog to generate the changelog and determine the bump level based on the commit messages.

**Comment by sunng87** [comment]
Personally I prefer an isolation between commit log, which is dev-facing, and release notes, which is user facing. So I didn't included auto changelog generation from very beginning. 

However, I agree it's possible to determine the release level from commit log or public api changes. I wish semantic could offer a binary of library just for determining bump level so we can add optional support for that.

**Comment by epage** [comment]
> Personally I prefer an isolation between commit log, which is dev-facing, and release notes, which is user facing. So I didn't included auto changelog generation from very beginning.

Ideally, yes but I maintain too many crates to always worry about the changelog.  Maybe switching to cargo-release will help.  However, I do tend to make my commits more user focused (if they are feat/fix rather than refactor/chore).  

And too often I see projects, major projects, without them and I'm at a loss digging through commits when they make breaking changes.  Something is better than nothing.

> However, I agree it's possible to determine the release level from commit log or public api changes. I wish semantic could offer a binary of library just for determining bump level so we can add optional support for that.

At my quick glance, it looked like semantic was just calling into `clog-cli`'s crate to see if anything was considered breaking from conventional-changelog's perspective, so that should be relatively easy to pull out.

**Comment by epage** [comment]
The downside to `semantic`'s approach is you have to hope you did things right for it to correctly guess what version field to bump.  If you mess up, you might end up needing to yank a release.  I have also found that while it is easy to get people to do checklist tasks in the source code (like update changelog), it is harder to be programmatically precise tasks like with commit messages.

Another approach is to instead have the source always represent what the next version will be.  If a commit makes a breaking change, then that commit is responsible for updating the version number without doing a release.  The CI then releases that version.  To support this, we might want a `--no-release` flag that is a shortcut for `--no-push`, `--no-tag`, etc that a developer will call in prep for their PR.

The use cases we'd want to consider supporting
- Dev bumps minor, major with or without pre-release
  - `--no-release` would help
  - It'd be nice to have a way to a bump to a pre-release major or minor
- The CI releases the current version
  - We'd need a new level: `unchanged`
- Post-release, the CI bumps the version to be a patch or an incremented pre-release, depending on the project's config
  - We'd want a `post-level` arg.
    - For projects that only want automatic pre-release versions, they can use the existing pre-release levels
    - For projects that don't normally use pre-release, they might want a `increment` level that increments pre-release, if present, and otherwise increments patch.

... I have more thoughts and there is some problem areas but I wanted to post this without a long delay as I write it all up

**Comment by psoots** [comment]
For what it's worth, if you don't need signed commits or are worried about protected branches, you can get away with a much more out-of-the-box release process.

```yaml
name: Release

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
    inputs:
      level:
        type: choice
        description: Bump level
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: cache cargo cache
        id: cache-release
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/target/
          key: ${{ runner.os }}-cargo-release

      - name: checkout code
        uses: actions/checkout@v3
      
      - name: git config
        run: |
          git config user.name "Github Actions: Release"
          git config user.email "<>"

      # fail early if tests fail
      - name: run tests
        run: |
          make test

      - name: install cargo-release
        uses: actions-rs/cargo@v1
        if: steps.cache-release.outputs.cache-hit != 'true'
        with:
          command: install
          args: cargo-release

      - name: cargo release ${{ github.event.inputs.level }}
        uses: actions-rs/cargo@v1
        with:
          command: release
          args: ${{ github.event.inputs.level }} --execute --no-confirm --config .github/workflows/cargo-release.toml
```
