### ISSUE TITLE
Confusing tag prefix behavior in workspaces

### ISSUE THREAD

**Issue by antifuchs** [sunng87/cargo-release#133]
I am moving my configuration from a single-crate repo to a workspace repo, so this is somewhat new to me. Here's my `release.toml` in a repo with two crates in them, `chars` and `chars_data`:

``` toml
sign-commit = false
upload-doc = false
pre-release-commit-message = "Release {{crate_name}} {{version}} 🎉🎉"
pro-release-commit-message = "Start next {{crate_name}} development iteration {{version}}"
tag-message = "Release {{crate_name}} {{prefix}}{{version}}"
dev-version-ext = "dev"
tag-prefix = "v"
```

Running `cargo release --dry-run minor` gives me this output:

```
Update chars_data to version 0.4.0
Fixing chars's dependency on chars_data to `^0.4.0` (from `^0.3.3-dev`)
Updating lock file
cd /Users/asf/Hacks/chars/chars_data
git commit  -am Release chars_data 0.4.0 🎉🎉
cd -
Running cargo publish on chars_data
/Users/asf/.rustup/toolchains/nightly-x86_64-apple-darwin/bin/cargo publish --manifest-path /Users/asf/Hacks/chars/chars_data/Cargo.toml
Creating git tag vv0.4.0
cd /Users/asf/Hacks/chars/chars_data
git tag -a vv0.4.0 -m Release chars_data v0.4.0
cd -
Starting chars_data's next development iteration 0.4.1-dev
cd /Users/asf/Hacks/chars/chars_data
git commit  -am Start next chars_data development iteration 0.4.0
cd -
Pushing to git remote
cd /Users/asf/Hacks/chars/chars_data
git push origin
cd -
cd /Users/asf/Hacks/chars/chars_data
git push origin vv0.4.0
cd -
Finished chars_data
Update chars to version 0.4.0
Updating lock file
cd /Users/asf/Hacks/chars/chars
git commit  -am Release chars 0.4.0 🎉🎉
cd -
Running cargo publish on chars
/Users/asf/.rustup/toolchains/nightly-x86_64-apple-darwin/bin/cargo publish --manifest-path /Users/asf/Hacks/chars/chars/Cargo.toml
Creating git tag vv0.4.0
cd /Users/asf/Hacks/chars/chars
git tag -a vv0.4.0 -m Release chars v0.4.0
cd -
Starting chars's next development iteration 0.4.1-dev
cd /Users/asf/Hacks/chars/chars
git commit  -am Start next chars development iteration 0.4.0
cd -
Pushing to git remote
cd /Users/asf/Hacks/chars/chars
git push origin
cd -
cd /Users/asf/Hacks/chars/chars
git push origin vv0.4.0
cd -
Finished chars
```

Note the weird `git tag` lines above: I was expecting the tag to look like `v0.4.0`, but it actually is `vv0.4.0`.

It looks like maybe `cargo release` in the crates is getting the tag prefix twice.

(Side note: I should probably not git-tag the data crate, or use a different tag format as it's just a build dependency).
