### ISSUE TITLE
Allow placeholders in replacement searches

### ISSUE THREAD

**Issue by woodruffw** [sunng87/cargo-release#241]
First of all, thanks a ton for `cargo release`! It's a fantastic tool.

It's currently impossible to do something like this:

```toml
[[package.metadata.release.pre-release-replacements]]
file = "README.md"
search = "{{prev_version}}"
replace = "{{version}}"
```

Since `cargo-release` only renders placeholders in `replace`, not `search`:

https://github.com/sunng87/cargo-release/blob/8557924d5ef1ddd1268bfeec29c558961874f015/src/replace.rs#L103 

Supporting placeholders in `search` would make a lot of common replacements simpler, since an (underapproximated) regular expression could be replaced by the exact search string.

Here's my proposal for `search`:

* Placeholders get expanded in `search` first
* The expanded string gets passed to `regex::escape`, allowing it to be used as a string literal
* The actual regex pattern is created as before, with `Regex::new`

This should be (1) safe, since every placeholder expansion will always be fully escaped, and (2) a lot more convenient than having to write approximate expressions for things like versions.
